
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Credito
{

    public Credito()
    {

        this.Abono = new HashSet<Abono>();

    }


    public int Id_credito { get; set; }

    public int id_detalle { get; set; }

    public decimal saldo { get; set; }

    public bool cancelado { get; set; }

    public bool anulado { get; set; }



    public virtual Detalle Detalle { get; set; }

    public virtual ICollection<Abono> Abono { get; set; }

}

}
