
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Detalle
{

    public Detalle()
    {

        this.Abono = new HashSet<Abono>();

    }


    public int IdDetalle { get; set; }

    public int IdTransaccion { get; set; }

    public int TipoDetalle { get; set; }

    public int TipoTransaccion { get; set; }

    public string Descripcion { get; set; }

    public decimal Cantidad { get; set; }

    public bool Activo { get; set; }

    public bool Cancelado { get; set; }



    public virtual TipoDetalle TipoEgreso { get; set; }

    public virtual Transaccion Transaccion { get; set; }

    public virtual ICollection<Abono> Abono { get; set; }

    public virtual Saldo_detalle Saldo_detalle { get; set; }

}

}
