

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModeloContainer : DbContext
{
    public ModeloContainer()
        : base("name=ModeloContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Personas> PersonasSet { get; set; }

    public DbSet<Usuarios> UsuariosSet { get; set; }

    public DbSet<Conductor> ConductorSet { get; set; }

    public DbSet<Socio> SocioSet { get; set; }

    public DbSet<Vehiculo> VehiculoSet { get; set; }

    public DbSet<TipoUsuario> TipoUsuarioSet { get; set; }

    public DbSet<Transaccion> TransaccionSet { get; set; }

    public DbSet<Detalle> DetalleSet { get; set; }

    public DbSet<TipoDetalle> TipoDetalleSet { get; set; }

    public DbSet<Carrera> CarreraSet { get; set; }

    public DbSet<Saldo> SaldoSet { get; set; }

    public DbSet<Credito> CreditoSet { get; set; }

    public DbSet<Abono> AbonoSet { get; set; }

}

}

