
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Personas
{

    public int Id_persona { get; set; }

    public string Identificacion { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public bool Activo { get; set; }



    public virtual Usuarios Usuarios { get; set; }

    public virtual Socio Socios { get; set; }

    public virtual Conductor Conductor { get; set; }
        public override string ToString()
        {
            return string.Format("{0} {1}", Nombres, Apellidos);
        }

    }

}
