
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Usuarios
{

    public int Id_usuario { get; set; }

    public string Nickname { get; set; }

    public string Clave { get; set; }

    public int Id_tipo { get; set; }



    public virtual Personas Personas { get; set; }

    public virtual TipoUsuario TipoUsuario { get; set; }
        public override string ToString()
        {
            return Personas.ToString();
        }
    }

}
